toolsQuadrant.add([
new TechRadar.Blip("Fortify On Demand", adopt, false, "<p><a href=\\\"https://www.microfocus.com/en-us/cyberres/application-security/fortify-on-demand\\\">Fortify On Demand</a> is a tool used to build secure software fast with an application security platform that automates testing throughout the CI/CD pipeline to enable developers to quickly resolve issues</p>"),
new TechRadar.Blip("Microsoft Visual Studio", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://visualstudio.microsoft.com/vs/\\\">Microsoft Visual Studio</a> is an integrated development environment (IDE) from Microsoft. It is used to develop computer programs, as well as websites, web apps, web services and mobile apps.</span></p>"),
new TechRadar.Blip("Visual Studio Code", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://code.visualstudio.com/\\\">Visual Studio Code</a> is a source-code editor made by Microsoft for Windows, Linux and macOS. Features include support for debugging, syntax highlighting, intelligent code completion, snippets, code refactoring, and embedded Git.</span></p>"),
]);

techniquesQuadrant.add([
new TechRadar.Blip("TypeScript", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://www.typescriptlang.org/\\\">TypeScript</a>&nbsp;is a programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript and adds optional static typing to the language. TypeScript is designed for the development of large applications and transcompiles to JavaScript.</span></p>"),
new TechRadar.Blip(".Net ", trial, false, "<p>.NET (previously named .NET Core) is a free and open-source, managed computer software framework for Windows, Linux, and macOS operating systems. It is a cross-platform successor to .NET Framework.</p>"),
new TechRadar.Blip("Automated Testing", adopt, false, "<p>Automated testing is a process that validates if software is functioning appropriately and meeting requirements before it is released into production. This software testing method uses scripted sequences that are executed by testing tools.</p>"),
new TechRadar.Blip("Agile Scrum Methodology", adopt, true, "<p>Based on <a href=\\\"https://www.scaledagileframework.com/\\\">SAFe</a> our Agile Scrum Methodology is a knowledge base of tested and integrated principles, practices and competencies for achieving business agility using Lean, Agile, and DevOps.</p>"),
new TechRadar.Blip("DevOps", adopt, false, "<p>Short and agile <strong>System Development Life cycle</strong> providing <strong>software quality</strong> and <strong>continuous deployment</strong> in <strong>Secure Software Supply Chain</strong>."),
new TechRadar.Blip("Managed Cloud Environments", adopt, true, "<p><strong>One Platform</strong>, <strong>Cloud Next </strong>and <strong>Country Hosting </strong>- Managed Services and Cloud Environments hosted in Azure&nbsp;are recognized as the trusted partner in the delivery of cloud-based and managed services solutions. These solutions are designed to realize customers’ operational excellence goals.</p>"),
new TechRadar.Blip("Microservice Solution", adopt, false, "<p>Based on client scope and high level architecture we successfully build <strong><a href=\\\"https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/microservices\\\">Microservice Solutions</a></strong> for custom container based environments or for Service Fabric</p>"),
new TechRadar.Blip("Mobile PWA Application", adopt, false, "<p>Building responsive web applications as <strong><a href=\\\"https://en.wikipedia.org/wiki/Progressive_web_application\\\">Mobile Progressive Web Application</a></strong> enable us to deliver close-to-native experience in mobile application development</p>"),
new TechRadar.Blip("Reference Architecture", adopt, false, "<p><strong><a href=\\\"https://en.wikipedia.org/wiki/Reference_architecture\\\">Reference Architecture</a></strong> is a code base with templates and packages that help us building non-functional components of each solution (like: logging, audit, identity, database access according to the environment security requirements, etc.).</p>"),
new TechRadar.Blip("Secure Web applications", adopt, false, "<p>Building stable, redundant and secure <strong>Web Applications</strong> in Cloud and on Premis with application design, implementation, vulnerability testing, and monitoring according to member firms standards and guidelines.</p>"),
new TechRadar.Blip("Software Delivery Guardrails", adopt, true, "<p>Empowering development teams to find, fix and prevent vulnerabilities related to source code, open source libraries, secret management and cloud configuration</p>"),
new TechRadar.Blip("Strong Security Policy", adopt, false, "<p>We meet the the security requirements set out by the <strong>Global Information Security Policies</strong> enforcing management directions and support for information security in accordance with business requirements and relevant laws and regulations.</p>"),
]);

platformsQuadrant.add([
new TechRadar.Blip("NEO", adopt, true, "<p><strong>NEO </strong>is Service Fabric Microservice Platform developed by German Software Engineering department .</p>"),
new TechRadar.Blip("MS Teams", adopt, false, "<p>Microsoft Teams is a proprietary business communication platform developed by Microsoft, as part of the Microsoft 365 family of products. Teams primarily competes with the similar service Slack, offering workspace chat and videoconferencing, file storage, and application integration.</p>"),
new TechRadar.Blip("AWS", trial, true, "<p>Amazon Web Services, Inc. is a subsidiary of Amazon providing on-demand cloud computing platforms and APIs to individuals, companies, and governments, on a metered pay-as-you-go basis.</p>"),
]);

languageFramework.add([
new TechRadar.Blip("Angular", adopt, false, "<p><a href=\\\"https://angular.io/\\\">Angular </a>is a TypeScript-based free and open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations.</p>"),
new TechRadar.Blip("JavaScript", adopt, false, "<p><a href=\\\"https://www.javascript.com/\\\">JavaScript</a>, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification. JavaScript is high-level, often just-in-time compiled, and multi-paradigm. It has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions.</p>"),
new TechRadar.Blip("Node.js", adopt, false, "<p><a href=\\\"https://nodejs.org/en/\\\">Node.js </a>is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser.</p>"),
new TechRadar.Blip("Vue.js", trial, true, "<p><a href=\\\"https://vuejs.org/\\\">Vue.js</a>&nbsp;is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications.</p>"),
new TechRadar.Blip("Java", hold, true, "<p>Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.</p>"),
new TechRadar.Blip("Next.js", asess, false, "<p>Next.js is an open-source development framework built on top of Node.js enabling React based web applications functionalities such as server-side rendering and generating static websites.</p>"),
]);

