toolsQuadrant.add([
new TechRadar.Blip("Microsoft Visual Studio", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://visualstudio.microsoft.com/vs/\\\">Microsoft Visual Studio</a> is an integrated development environment (IDE) from Microsoft. It is used to develop computer programs, as well as websites, web apps, web services and mobile apps.</span></p>"),
]);

techniquesQuadrant.add([
new TechRadar.Blip("SQL", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\">SQL (Structured Query Language) is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS), or for stream processing in a relational data stream management system (RDSMS).</span></p><ul><li><span style=\\\"background-color:#ffffff; color:#666666; font-size:13px\\\"><a href=\\\"https://docs.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-ver15\\\">Transact-SQL</a> is Microsoft's and Sybase's proprietary extension to the SQL used to interact with relational databases.</span></li><li><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://www.oracle.com/database/technologies/application-development-pl/sql.html\\\">PL/SQL</a> (Procedural Language for SQL) is Oracle Corporation's procedural extension for SQL and the Oracle relational database.</span></li></ul>"),
new TechRadar.Blip("TypeScript", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://www.typescriptlang.org/\\\">TypeScript</a>&nbsp;is a programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript and adds optional static typing to the language. TypeScript is designed for the development of large applications and transcompiles to JavaScript.</span></p>"),
new TechRadar.Blip(".Net ", trial, false, "<p>.NET (previously named .NET Core) is a free and open-source, managed computer software framework for Windows, Linux, and macOS operating systems. It is a cross-platform successor to .NET Framework.</p>"),
new TechRadar.Blip("Automated Testing", adopt, false, "<p>Automated testing is a process that validates if software is functioning appropriately and meeting requirements before it is released into production. This software testing method uses scripted sequences that are executed by testing tools.</p>"),
new TechRadar.Blip("Agile Scrum Methodology", adopt, true, "<p>Based on <a href=\\\"https://www.scaledagileframework.com/\\\">SAFe</a> our Agile Scrum Methodology is a knowledge base of tested and integrated principles, practices and competencies for achieving business agility using Lean, Agile, and DevOps.</p>"),
new TechRadar.Blip("DevOps", adopt, false, "<p>Short and agile <strong>System Development Life cycle</strong> providing <strong>software quality</strong> and <strong>continuous deployment</strong> in <strong>Secure Software Supply Chain</strong>."),
new TechRadar.Blip("Managed Cloud Environments", adopt, true, "<p><strong>One Platform</strong>, <strong>Cloud Next </strong>and <strong>Country Hosting </strong>- Managed Services and Cloud Environments hosted in Azure&nbsp;are recognized as the trusted partner in the delivery of cloud-based and managed services solutions. These solutions are designed to realize customers’ operational excellence goals.</p>"),
new TechRadar.Blip("Reference Architecture", adopt, false, "<p><strong><a href=\\\"https://en.wikipedia.org/wiki/Reference_architecture\\\">Reference Architecture</a></strong> is a code base with templates and packages that help us building non-functional components of each solution (like: logging, audit, identity, database access according to the environment security requirements, etc.).</p>"),
new TechRadar.Blip("Secure Web applications", adopt, false, "<p>Building stable, redundant and secure <strong>Web Applications</strong> in Cloud and on Premis with application design, implementation, vulnerability testing, and monitoring according to member firms standards and guidelines.</p>"),
new TechRadar.Blip("Software Delivery Guardrails", adopt, true, "<p>Empowering development teams to find, fix and prevent vulnerabilities related to source code, open source libraries, secret management and cloud configuration</p>"),
new TechRadar.Blip("Strong Security Policy", adopt, false, "<p>We meet the the security requirements set out by the <strong>Global Information Security Policies</strong> enforcing management directions and support for information security in accordance with business requirements and relevant laws and regulations.</p>"),
]);

platformsQuadrant.add([
new TechRadar.Blip("SharePoint", adopt, false, "<p><a href=\\\"https://www.microsoft.com/en-us/microsoft-365/sharepoint/collaboration\\\"><span style=\\\"color:#767676\\\"><span><span style=\\\"font-size:small\\\">SharePoint</span></span></span></a><span style=\\\"font-size:13px\\\"><span style=\\\"color:#666666\\\"><span><span><span><span><span><span><span style=\\\"background-color:#ffffff\\\"><span><span><span><span>&nbsp;empowers teamwork with dynamic and productive team sites for every project team, department, and division. Share files, data, news, and resources. Customize your site to streamline your team’s work.</span></span></span></span></span></span></span></span></span></span></span></span></span></p>"),
new TechRadar.Blip("MS Teams", adopt, false, "<p>Microsoft Teams is a proprietary business communication platform developed by Microsoft, as part of the Microsoft 365 family of products. Teams primarily competes with the similar service Slack, offering workspace chat and videoconferencing, file storage, and application integration.</p>"),
new TechRadar.Blip("Azure Cloud", trial, false, "<p>Microsoft Azure is a cloud computing service operated by Microsoft for application management via Microsoft-managed data centers</p>"),
]);

languageFramework.add([
new TechRadar.Blip("Angular", adopt, false, "<p><a href=\\\"https://angular.io/\\\">Angular </a>is a TypeScript-based free and open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations.</p>"),
new TechRadar.Blip("C#", adopt, false, "<p>C# is a general-purpose, multi-paradigm programming language.</p>"),
new TechRadar.Blip("Java", hold, true, "<p>Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.</p>"),
new TechRadar.Blip("Next.js", assess, false, "<p>Next.js is an open-source development framework built on top of Node.js enabling React based web applications functionalities such as server-side rendering and generating static websites.</p>"),
]);

