toolsQuadrant.add([
new TechRadar.Blip("Fortify On Demand", adopt, false, "<p><a href=\\\"https://www.microfocus.com/en-us/cyberres/application-security/fortify-on-demand\\\">Fortify On Demand</a> is a tool used to build secure software fast with an application security platform that automates testing throughout the CI/CD pipeline to enable developers to quickly resolve issues</p>"),
new TechRadar.Blip("Swagger", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://swagger.io/\\\">Swagger</a> is an Interface Description Language for describing RESTful APIs expressed using JSON. Swagger is used together with a set of open-source software tools to design, build, document, and use RESTful web services</span></p>"),
new TechRadar.Blip("Microsoft Visual Studio", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://visualstudio.microsoft.com/vs/\\\">Microsoft Visual Studio</a> is an integrated development environment (IDE) from Microsoft. It is used to develop computer programs, as well as websites, web apps, web services and mobile apps.</span></p>"),
new TechRadar.Blip("WhiteSource", adopt, false, "<p><a href=\\\"https://www.whitesourcesoftware.com/\\\">WhiteSource</a><strong> </strong>is an open source security and license compliance management platform.</p><p>All deliverables by ITS&nbsp;are compliant&nbsp;with both Global and German requirements.</p><p>Detailed reports are evaluated and presented on Change Advisory&nbsp;Board for passing quality gate before delivery on each environment.</p><p> </p>"),
new TechRadar.Blip("Figma", adopt, true, "<p>TBD</p>"),
]);

techniquesQuadrant.add([
new TechRadar.Blip("Automated Testing", adopt, false, "<p>Automated testing is a process that validates if software is functioning appropriately and meeting requirements before it is released into production. This software testing method uses scripted sequences that are executed by testing tools.</p>"),
new TechRadar.Blip("Agile Methodology", adopt, true, "<p>Based on <a href=\\\"https://www.scaledagileframework.com/\\\">SAFe</a> our Agile Methodology is a knowledge base of tested and integrated principles, practices and competencies for achieving business agility using Lean, Agile, and DevOps.</p>"),
new TechRadar.Blip("DevOps", adopt, false, "<p>Short and agile <strong>System Development Life cycle</strong> providing <strong>software quality</strong> and <strong>continuous deployment</strong> in <strong>Secure Software Supply Chain</strong>."),
new TechRadar.Blip("Managed Cloud Environments", adopt, true, "<p><strong>One Platform</strong>, <strong>Cloud Next </strong>and <strong>Country Hosting </strong>- Managed Services and Cloud Environments hosted in Azure&nbsp;are recognized as the trusted partner in the delivery of cloud-based and managed services solutions. These solutions are designed to realize customers’ operational excellence goals.</p>"),
new TechRadar.Blip("Microservice Solution", adopt, false, "<p>Based on client scope and high level architecture we successfully build <strong><a href=\\\"https://docs.microsoft.com/en-us/azure/architecture/guide/architecture-styles/microservices\\\">Microservice Solutions</a></strong> for custom container based environments or for Service Fabric</p>"),
new TechRadar.Blip("Mobile Progressive Web Application", adopt, false, "<p>Building responsive web applications as <strong><a href=\\\"https://en.wikipedia.org/wiki/Progressive_web_application\\\">Mobile Progressive Web Application</a></strong> enable us to deliver close-to-native experience in mobile application development</p>"),
new TechRadar.Blip("Quality Assurance Strategy", adopt, true, "<p>A Quality Assurance strategy plan is a comprehensive, and integrated planning process focused on increasing the value for the customer by achieving a competitive advantage. Such a strategic template helps us&nbsp;with anticipating future demand for Quality Assurance services and resource management.</p>"),
new TechRadar.Blip("Reference Architecture", adopt, false, "<p><strong><a href=\\\"https://en.wikipedia.org/wiki/Reference_architecture\\\">Reference Architecture</a></strong> is a code base with templates and packages that help us building non-functional components of each solution (like: logging, audit, identity, database access according to the environment security requirements, etc.).</p>"),
new TechRadar.Blip("Secure Web applications", adopt, false, "<p>Building stable, redundant and secure <strong>Web Applications</strong> in Cloud and on Premis with application design, implementation, vulnerability testing, and monitoring according to member firms standards and guidelines.</p>"),
new TechRadar.Blip("Software Delivery Guardrails", adopt, true, "<p>Empowering development teams to find, fix and prevent vulnerabilities related to source code, open source libraries, secret management and cloud configuration</p>"),
new TechRadar.Blip("Strong Security Policy", adopt, false, "<p>We meet the the security requirements set out by the <strong>Global Information Security Policies</strong> enforcing management directions and support for information security in accordance with business requirements and relevant laws and regulations.</p>"),
new TechRadar.Blip("Secure Software Component Supply", adopt, true, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:16px\\\">We&nbsp;secure and monitor our&nbsp;software supply chain to avoid an upstream of vulnerability in one of your dependencies that can affect our application, making&nbsp;us susceptible to a potential compromise.</span></p><p> </p>"),
]);

platformsQuadrant.add([
new TechRadar.Blip("Azure Cloud - Country Hosting", adopt, false, "<p><strong>TBD</strong></p>"),
new TechRadar.Blip("Azure Cloud - One Platform (managed)", adopt, false, "<p><strong>TBD</strong></p>"),
new TechRadar.Blip("Azure Cloud - One Platform (sandbox)", adopt, false, "<p><strong>TBD</strong></p>"),
new TechRadar.Blip("NEO", adopt, true, "<p><strong>NEO </strong>is Service Fabric Microservice Platform developed by German Software Engineering department .</p>"),
new TechRadar.Blip("SharePoint Online", adopt, false, "<p><strong>TBD</strong></p>"),
new TechRadar.Blip("MS Teams", adopt, false, "<p>Microsoft Teams is a proprietary business communication platform developed by Microsoft, as part of the Microsoft 365 family of products. Teams primarily competes with the similar service Slack, offering workspace chat and videoconferencing, file storage, and application integration.</p>"),
new TechRadar.Blip("AWS", trial, true, "<p>Amazon Web Services, Inc. is a subsidiary of Amazon providing on-demand cloud computing platforms and APIs to individuals, companies, and governments, on a metered pay-as-you-go basis.</p>"),
new TechRadar.Blip("Azure Cloud - Cloud Next", assess, false, "<p><strong>TBD</strong></p>"),
new TechRadar.Blip("Azure Cloud", hold, false, "<p>Microsoft Azure is a cloud computing service operated by Microsoft for application management via Microsoft-managed data centers</p>"),
new TechRadar.Blip("SOFY", adopt, true, "<p>SOFY Suite enables you to operationalize data analytics and use it at the right time for the right purpose. The predefined applications of the SOFY Suite are based on our modern self-service BI, survey and workflow engine and KPMG's may years of experience in the areas of auditing and consulting.</p>"),
]);

languageFramework.add([
new TechRadar.Blip("Angular", adopt, false, "<p><a href=\\\"https://angular.io/\\\">Angular </a>is a TypeScript-based free and open-source web application framework led by the Angular Team at Google and by a community of individuals and corporations.</p>"),
new TechRadar.Blip("C#", adopt, false, "<p>C# is a general-purpose, multi-paradigm programming language.</p>"),
new TechRadar.Blip("JavaScript", adopt, false, "<p><a href=\\\"https://www.javascript.com/\\\">JavaScript</a>, often abbreviated as JS, is a programming language that conforms to the ECMAScript specification. JavaScript is high-level, often just-in-time compiled, and multi-paradigm. It has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions.</p>"),
new TechRadar.Blip("Node.js", adopt, false, "<p><a href=\\\"https://nodejs.org/en/\\\">Node.js </a>is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser.</p>"),
new TechRadar.Blip("SQL", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\">SQL (Structured Query Language) is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS), or for stream processing in a relational data stream management system (RDSMS).</span></p><ul><li><span style=\\\"background-color:#ffffff; color:#666666; font-size:13px\\\"><a href=\\\"https://docs.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-ver15\\\">Transact-SQL</a> is Microsoft's and Sybase's proprietary extension to the SQL used to interact with relational databases.</span></li><li><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://www.oracle.com/database/technologies/application-development-pl/sql.html\\\">PL/SQL</a> (Procedural Language for SQL) is Oracle Corporation's procedural extension for SQL and the Oracle relational database.</span></li></ul>"),
new TechRadar.Blip("TypeScript", adopt, false, "<p><span style=\\\"background-color:#ffffff; color:#444444; font-size:13px\\\"><a href=\\\"https://www.typescriptlang.org/\\\">TypeScript</a>&nbsp;is a programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript and adds optional static typing to the language. TypeScript is designed for the development of large applications and transcompiles to JavaScript.</span></p>"),
new TechRadar.Blip("Vue.js", trial, true, "<p><a href=\\\"https://vuejs.org/\\\">Vue.js</a>&nbsp;is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications.</p>"),
new TechRadar.Blip(".Net ", adopt, false, "<p>.NET (previously named .NET Core) is a free and open-source, managed computer software framework for Windows, Linux, and macOS operating systems. It is a cross-platform successor to .NET Framework.</p>"),
new TechRadar.Blip("Blazor", adopt, true, "<p><a href=\\\"https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor\\\">Blazor </a>is a free and open-source web framework that enables developers to create web apps using C# and HTML</p>"),
new TechRadar.Blip("Java", hold, true, "<p>Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.</p>"),
new TechRadar.Blip("Next.js", assess, false, "<p>Next.js is an open-source development framework built on top of Node.js enabling React based web applications functionalities such as server-side rendering and generating static websites.</p>"),
]);

